# Generated by Django 3.2.12 on 2022-04-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smt_app', '0007_auto_20220414_0913'),
        ('shop_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='ass_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.assistancesupervisor'),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.tax'),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city'),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.shop'),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_owner',
            field=models.ManyToManyField(related_name='shopownershopdetail', to='user_app.ShopOwner'),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.zone'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city'),
        ),
        migrations.AddField(
            model_name='shop',
            name='history',
            field=models.ManyToManyField(related_name='history_shop', to='shop_app.ShopDetail'),
        ),
        migrations.AddField(
            model_name='shop',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.zone'),
        ),
        migrations.AddField(
            model_name='cleanerrecord',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.cleaner'),
        ),
        migrations.AddField(
            model_name='cleanerrecord',
            name='shop_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.shopdetail'),
        ),
        migrations.AddField(
            model_name='cleanergroup',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaner_group_supervisor', to='user_app.supervisor'),
        ),
    ]
