# Generated by Django 3.2.12 on 2022-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='shop_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='history_shop', to='shop_app.ShopDetail'),
        ),
    ]
