# Generated by Django 3.2.12 on 2022-04-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('shop_app', '0003_auto_20220415_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ass_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.assistancesupervisor'),
        ),
    ]
