# Generated by Django 3.2.12 on 2022-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_shop_ass_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerrecord',
            name='date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
