# Generated by Django 3.2.12 on 2022-04-18 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_cleanerrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerrecord',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 18)),
        ),
        migrations.AlterField(
            model_name='cleanerrecord',
            name='shop_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.shopdetail'),
        ),
    ]
