# Generated by Django 3.2.12 on 2022-04-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_auto_20220418_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetail',
            name='shop_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.shop'),
        ),
    ]
