# Generated by Django 3.2.12 on 2022-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_shopdetail_shop_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='is_status',
            field=models.BooleanField(default='True', verbose_name='status'),
        ),
    ]
