# Generated by Django 3.2.12 on 2022-04-20 06:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('shop_app', '0008_shopdetail_is_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerrecord',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 20)),
        ),
        migrations.CreateModel(
            name='AssignCleanerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 4, 20))),
                ('assign_status', models.BooleanField()),
                ('ass_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.assistancesupervisor')),
                ('cleaner_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.cleanergroup')),
            ],
        ),
    ]
