# Generated by Django 3.2.12 on 2022-04-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('shop_app', '0009_auto_20220420_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigncleanerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('record', models.BooleanField()),
                ('ass_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.assistancesupervisor')),
                ('cleaner_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.cleanergroup')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.shop')),
            ],
        ),
    ]
