# Generated by Django 3.2.12 on 2022-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_alter_assigncleanerd_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigncleanerd',
            name='record',
            field=models.BooleanField(null=True),
        ),
    ]
