# Generated by Django 3.2.12 on 2022-04-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smt_app', '0004_shop_manager_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_manager',
            name='ass_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.assistancesupervisor'),
        ),
    ]
