# Generated by Django 3.2.13 on 2022-05-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
