# Generated by Django 3.2.13 on 2022-05-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
