# Generated by Django 3.2.13 on 2022-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_auto_20220511_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
    ]
