# Generated by Django 3.2.13 on 2022-05-06 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 5, 6)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
