# Generated by Django 3.2.13 on 2022-05-11 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 5, 11)),
        ),
    ]
