# Generated by Django 3.2.12 on 2022-04-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smt_app', '0005_shop_manager_ass_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('records', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_meter', models.IntegerField()),
                ('shop_no', models.IntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='shop_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shop_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.shop_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city')),
            ],
        ),
        migrations.RenameField(
            model_name='shop_owner',
            old_name='city',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='assistancesupervisor',
            name='area',
        ),
        migrations.RemoveField(
            model_name='cleaner',
            name='area',
        ),
        migrations.RemoveField(
            model_name='cleaner',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='shop_owner',
            name='area',
        ),
        migrations.RemoveField(
            model_name='shop_owner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop_owner',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='area',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='ass_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.assistancesupervisor'),
        ),
        migrations.AddField(
            model_name='shop_owner',
            name='shop_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop_owner',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('SUPERVISOR', 'SUPERVISOR'), ('ASSISTANT SUPERVISOR', 'ASSISTANT SUPERVISOR'), ('CLEANER', 'CLEANER'), ('SHOP OWNER', 'SHOP OWNER')], default='MANAGER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Shop_Manager',
        ),
        migrations.AddField(
            model_name='shop_detail',
            name='ass_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.assistancesupervisor'),
        ),
        migrations.AddField(
            model_name='shop_detail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.tax'),
        ),
        migrations.AddField(
            model_name='shop_detail',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city'),
        ),
        migrations.AddField(
            model_name='shop_detail',
            name='shop_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.shop'),
        ),
        migrations.AddField(
            model_name='shop_detail',
            name='shop_owner',
            field=models.ManyToManyField(related_name='shopowner_shopdetail', to='smt_app.Shop_Owner'),
        ),
        migrations.AddField(
            model_name='shop_detail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop_detail',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.zone'),
        ),
        migrations.AddField(
            model_name='shop',
            name='history',
            field=models.ManyToManyField(related_name='history_shop', to='smt_app.shop_detail'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopdetail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.zone'),
        ),
        migrations.AddField(
            model_name='cleaner_record',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.cleaner'),
        ),
        migrations.AddField(
            model_name='cleaner_record',
            name='shop_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.shop_detail'),
        ),
        migrations.AddField(
            model_name='cleaner_group',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaner_group_supervisor', to='smt_app.supervisor'),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='cleaner_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smt_app.cleaner_group'),
        ),
        migrations.AlterField(
            model_name='assistancesupervisor',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city'),
        ),
        migrations.AlterField(
            model_name='assistancesupervisor',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.zone'),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city'),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.zone'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.city'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='zone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='smt_app.zone'),
        ),
    ]
